name: Malta Property Matcher Scraper

on:
  schedule:
    # Esegue lo script ogni 6 ore
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permette di avviarlo anche manualmente con un click

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Scraper Script
      run: python scraper.py
